# DEMO – Generated by Codex CLI for Vertice360 (NO PRODUCCIÓN)
"""Rutas de demo para exponer datos ficticios de Vertice360 bajo /api/demo/codex."""

from __future__ import annotations

from typing import Any

from litestar import Router, get

from db.demo_vertice360_data import (
    get_demo_investors,
    get_demo_operations_for_investor,
    get_demo_projects,
    get_demo_units_for_project,
)


@get("/projects")
async def list_demo_projects() -> list[dict[str, Any]]:
    """Devuelve proyectos en pozo de la demo Codex."""
    return get_demo_projects()


@get("/projects/{project_id:str}/units")
async def list_demo_units(project_id: str) -> list[dict[str, Any]]:
    """Unidades asociadas a un proyecto demo."""
    return get_demo_units_for_project(project_id)


@get("/investors")
async def list_demo_investors() -> list[dict[str, Any]]:
    """Listado de inversores ficticios."""
    return get_demo_investors()


@get("/investors/{investor_id:str}/operations")
async def list_demo_operations(investor_id: str) -> list[dict[str, Any]]:
    """Operaciones de reserva/venta de un inversor demo."""
    return get_demo_operations_for_investor(investor_id)


router = Router(
    path="/api/demo/codex",
    route_handlers=[
        list_demo_projects,
        list_demo_units,
        list_demo_investors,
        list_demo_operations,
    ],
)
