# DEMO – Generated by Codex CLI for Pozo360 (NO PRODUCCIÓN)
"""
Conjunto de datos ficticios para la demo Codex de Pozo360.
Todos los valores son mock y no deben usarse en producción.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any

# Proyectos en pozo (mock)
proyectos_en_pozo: list[dict[str, Any]] = [
    {
        "id_proyecto": "PZ-ALV-101",
        "nombre": "Torre Alvear",
        "barrio": "Recoleta",
        "ciudad": "Buenos Aires",
        "fecha_inicio_obra": "2024-03-01",
        "fecha_entrega_estimada": "2026-09-30",
        "moneda": "USD",
        "precio_desde": 95000,
        "precio_hasta": 320000,
        "estado": "en_obra",
    },
    {
        "id_proyecto": "PZ-RIO-204",
        "nombre": "Ribera del Río",
        "barrio": "Puerto Madero",
        "ciudad": "Buenos Aires",
        "fecha_inicio_obra": "2023-11-15",
        "fecha_entrega_estimada": "2025-12-15",
        "moneda": "USD",
        "precio_desde": 150000,
        "precio_hasta": 450000,
        "estado": "preventas",
    },
    {
        "id_proyecto": "PZ-CR-330",
        "nombre": "Cerro Norte",
        "barrio": "Nueva Córdoba",
        "ciudad": "Córdoba",
        "fecha_inicio_obra": "2023-07-01",
        "fecha_entrega_estimada": "2025-05-30",
        "moneda": "USD",
        "precio_desde": 78000,
        "precio_hasta": 215000,
        "estado": "en_obra",
    },
    {
        "id_proyecto": "PZ-MZ-450",
        "nombre": "Miradores del Zonda",
        "barrio": "Chacras",
        "ciudad": "Mendoza",
        "fecha_inicio_obra": "2022-10-20",
        "fecha_entrega_estimada": "2024-12-20",
        "moneda": "USD",
        "precio_desde": 62000,
        "precio_hasta": 180000,
        "estado": "entregado",
    },
]

# Unidades por proyecto (mock)
unidades: list[dict[str, Any]] = [
    {
        "id_unidad": "ALV-07A",
        "id_proyecto": "PZ-ALV-101",
        "piso": 7,
        "ambiente": "2 ambientes",
        "m2_cubiertos": 58,
        "m2_totales": 64,
        "precio_lista": 152000,
        "moneda": "USD",
        "estado_unidad": "disponible",
    },
    {
        "id_unidad": "ALV-12C",
        "id_proyecto": "PZ-ALV-101",
        "piso": 12,
        "ambiente": "3 ambientes",
        "m2_cubiertos": 86,
        "m2_totales": 94,
        "precio_lista": 238000,
        "moneda": "USD",
        "estado_unidad": "reservada",
    },
    {
        "id_unidad": "ALV-15P",
        "id_proyecto": "PZ-ALV-101",
        "piso": 15,
        "ambiente": "Penthouse",
        "m2_cubiertos": 128,
        "m2_totales": 142,
        "precio_lista": 315000,
        "moneda": "USD",
        "estado_unidad": "vendida",
    },
    {
        "id_unidad": "RIO-04B",
        "id_proyecto": "PZ-RIO-204",
        "piso": 4,
        "ambiente": "2 ambientes",
        "m2_cubiertos": 61,
        "m2_totales": 68,
        "precio_lista": 175000,
        "moneda": "USD",
        "estado_unidad": "disponible",
    },
    {
        "id_unidad": "RIO-09F",
        "id_proyecto": "PZ-RIO-204",
        "piso": 9,
        "ambiente": "3 ambientes",
        "m2_cubiertos": 94,
        "m2_totales": 102,
        "precio_lista": 268000,
        "moneda": "USD",
        "estado_unidad": "disponible",
    },
    {
        "id_unidad": "CR-05D",
        "id_proyecto": "PZ-CR-330",
        "piso": 5,
        "ambiente": "1 dormitorio",
        "m2_cubiertos": 47,
        "m2_totales": 52,
        "precio_lista": 82000,
        "moneda": "USD",
        "estado_unidad": "reservada",
    },
    {
        "id_unidad": "CR-11A",
        "id_proyecto": "PZ-CR-330",
        "piso": 11,
        "ambiente": "2 dormitorios",
        "m2_cubiertos": 74,
        "m2_totales": 81,
        "precio_lista": 132000,
        "moneda": "USD",
        "estado_unidad": "disponible",
    },
    {
        "id_unidad": "MZ-02C",
        "id_proyecto": "PZ-MZ-450",
        "piso": 2,
        "ambiente": "1 dormitorio",
        "m2_cubiertos": 52,
        "m2_totales": 58,
        "precio_lista": 67000,
        "moneda": "USD",
        "estado_unidad": "vendida",
    },
    {
        "id_unidad": "MZ-07D",
        "id_proyecto": "PZ-MZ-450",
        "piso": 7,
        "ambiente": "2 dormitorios",
        "m2_cubiertos": 79,
        "m2_totales": 85,
        "precio_lista": 119000,
        "moneda": "USD",
        "estado_unidad": "disponible",
    },
]

# Inversores (mock)
inversores: list[dict[str, Any]] = [
    {
        "id_inversor": "INV-901",
        "nombre": "Lucía Pereyra",
        "tipo_inversor": "minorista",
        "email": "lucia.pereyra@example.com",
        "pais": "Argentina",
    },
    {
        "id_inversor": "INV-902",
        "nombre": "Fideicomiso Andes",
        "tipo_inversor": "institucional",
        "email": "contacto@andesfund.com",
        "pais": "Chile",
    },
    {
        "id_inversor": "INV-903",
        "nombre": "Diego Luna",
        "tipo_inversor": "minorista",
        "email": "dluna@example.com",
        "pais": "Uruguay",
    },
    {
        "id_inversor": "INV-904",
        "nombre": "Atlas Capital",
        "tipo_inversor": "institucional",
        "email": "info@atlascap.io",
        "pais": "Estados Unidos",
    },
]

# Reservas y ventas (mock)
reservas_y_ventas: list[dict[str, Any]] = [
    {
        "id_operacion": "OP-5001",
        "id_inversor": "INV-901",
        "id_unidad": "ALV-12C",
        "tipo_operacion": "reserva",
        "fecha": "2024-04-18",
        "monto": 238000,
        "moneda": "USD",
    },
    {
        "id_operacion": "OP-5002",
        "id_inversor": "INV-902",
        "id_unidad": "RIO-09F",
        "tipo_operacion": "reserva",
        "fecha": "2024-05-03",
        "monto": 268000,
        "moneda": "USD",
    },
    {
        "id_operacion": "OP-5003",
        "id_inversor": "INV-903",
        "id_unidad": "CR-05D",
        "tipo_operacion": "venta",
        "fecha": "2024-01-22",
        "monto": 82000,
        "moneda": "USD",
    },
    {
        "id_operacion": "OP-5004",
        "id_inversor": "INV-904",
        "id_unidad": "MZ-07D",
        "tipo_operacion": "venta",
        "fecha": "2023-12-10",
        "monto": 119000,
        "moneda": "USD",
    },
]


def get_demo_projects() -> list[dict[str, Any]]:
    """Devuelve todos los proyectos de demo."""
    return deepcopy(proyectos_en_pozo)


def get_demo_units_for_project(id_proyecto: str) -> list[dict[str, Any]]:
    """Unidades de un proyecto específico."""
    return [deepcopy(unit) for unit in unidades if unit["id_proyecto"] == id_proyecto]


def get_demo_investors() -> list[dict[str, Any]]:
    """Listado de inversores ficticios."""
    return deepcopy(inversores)


def get_demo_operations_for_investor(id_inversor: str) -> list[dict[str, Any]]:
    """Reservas/ventas asociadas a un inversor."""
    return [deepcopy(op) for op in reservas_y_ventas if op["id_inversor"] == id_inversor]


__all__ = [
    "get_demo_projects",
    "get_demo_units_for_project",
    "get_demo_investors",
    "get_demo_operations_for_investor",
    "proyectos_en_pozo",
    "unidades",
    "inversores",
    "reservas_y_ventas",
]
